import { Product } from '../types';

import heroImg from '../assets/images/hero_wafer_break_1787378687320.jpg';
import classicImg from '../assets/images/classic_chocolate_1787378701811.jpg';
import hazelnutImg from '../assets/images/hazelnut_chocolate_1787378713590.jpg';
import darkImg from '../assets/images/dark_chocolate_1787378727109.jpg';
import caramelImg from '../assets/images/caramel_chocolate_1787378739432.jpg';
import brandCraftImg from '../assets/images/brand_craft_story_1787378754966.jpg';

export const ASSET_IMAGES = {
  hero: heroImg,
  classic: classicImg,
  hazelnut: hazelnutImg,
  dark: darkImg,
  caramel: caramelImg,
  brandCraft: brandCraftImg,
};

export const PRODUCTS: Product[] = [
  {
    id: 'prod-classic-choc',
    name: 'Classic Chocolate',
    flavor: 'Velvety Milk Chocolate',
    category: 'classic',
    tagline: 'The timeless signature with golden crisp layers & pure Belgian chocolate.',
    description: 'Crisp micro-layered wafer shell with a molten core of silky smooth Swiss-Belgian milk chocolate.',
    longDescription: 'Our flagship recipe begins with seven ultra-thin, golden-baked wafer lattices baked to a shatteringly crisp perfection. At its center rests a generous molten ganache of 48% single-origin cacao infused with whole Bourbon vanilla beans.',
    price: 14.50,
    originalPrice: 16.00,
    rating: 4.9,
    reviewCount: 328,
    image: classicImg,
    badge: 'Bestseller',
    cocoaPercentage: 48,
    crispFactor: 9.8,
    sweetnessLevel: 'Balanced & Silky Sweet',
    tastingNotes: ['Bourbon Vanilla', 'Creamy Milk Cacao', 'Toasted Malt Crunch', 'Warm Honey undertones'],
    ingredients: [
      'Belgian Milk Chocolate (Cacao Mass, Cocoa Butter, Whole Milk Powder, Natural Vanilla)',
      'Unbleached Wheat Flour',
      'Non-GMO Sunflower Lecithin',
      'Organic Cane Sugar',
      'Sea Salt',
      'Cold-Pressed Coconut Oil'
    ],
    nutrition: {
      servingSize: '4 Bites (30g)',
      calories: 145,
      totalFat: '8g',
      sugar: '11g',
      protein: '2.5g',
    },
    weight: '160g (Approx. 18 Artisan Bites)',
    inStock: true,
  },
  {
    id: 'prod-hazelnut-choc',
    name: 'Hazelnut Chocolate',
    flavor: 'Roasted Piedmont Hazelnut Praline',
    category: 'hazelnut',
    tagline: 'Slow-roasted Italian hazelnuts folded into decadent milk chocolate cream.',
    description: 'Golden honeycomb wafer filled with a luscious gianduja praline of roasted hazelnuts and milk cacao.',
    longDescription: 'Crafted with prized IGP Piedmont hazelnuts, lightly roasted over open fire and stone-ground into an ultra-smooth praline. Encased inside our delicate, golden-brown crispy wafer waffle casing that cracks softly at first touch.',
    price: 15.75,
    originalPrice: 17.50,
    rating: 5.0,
    reviewCount: 412,
    image: hazelnutImg,
    badge: 'Chef’s Favorite',
    cocoaPercentage: 52,
    crispFactor: 9.9,
    sweetnessLevel: 'Nutty & Luxurious',
    tastingNotes: ['Toasted Hazelnut', 'Warm Praline Gianduja', 'Brown Butter Wafer', 'Subtle Nutmeg'],
    ingredients: [
      'Roasted IGP Piedmont Hazelnuts (35%)',
      'Milk Chocolate (Cacao Mass, Cocoa Butter, Whole Milk Powder)',
      'Wheat Flour',
      'Pure Cocoa Butter',
      'Madagascar Vanilla Extract',
      'Fleur de Sel'
    ],
    nutrition: {
      servingSize: '4 Bites (30g)',
      calories: 155,
      totalFat: '9.5g',
      sugar: '9g',
      protein: '3.2g',
    },
    weight: '160g (Approx. 18 Artisan Bites)',
    inStock: true,
  },
  {
    id: 'prod-dark-choc',
    name: 'Dark Chocolate',
    flavor: '72% Single-Origin Dark Ganache',
    category: 'dark',
    tagline: 'Deep, bittersweet roasted cocoa with an astonishingly clean snap.',
    description: 'Intense dark chocolate ganache made from Ecuadorian Arriba cacao, wrapped in crisp cocoa wafers.',
    longDescription: 'For true chocolate connoisseurs. We pair our dark cocoa wafer shell with a velvety 72% dark ganache. Notes of dark berry fruitiness give way to deep roasted cacao nibs and an ultra-satisfying crispy crunch.',
    price: 15.00,
    originalPrice: 16.50,
    rating: 4.8,
    reviewCount: 289,
    image: darkImg,
    badge: 'Intense 72%',
    cocoaPercentage: 72,
    crispFactor: 9.7,
    sweetnessLevel: 'Deep Bittersweet & Complex',
    tastingNotes: ['Ecuadorian Dark Cacao', 'Ripe Black Cherry', 'Smoky Oak Wood', 'Crisp Bitter-Crunch'],
    ingredients: [
      'Single-Origin Dark Cacao (Ecuador Arriba 72%)',
      'Organic Cocoa Butter',
      'Dutch Dark Cocoa Powder',
      'Unbleached Wheat Flour',
      'Raw Demerara Sugar',
      'Gourmet Sea Salt'
    ],
    nutrition: {
      servingSize: '4 Bites (30g)',
      calories: 140,
      totalFat: '8.5g',
      sugar: '6g',
      protein: '3.0g',
    },
    weight: '160g (Approx. 18 Artisan Bites)',
    inStock: true,
  },
  {
    id: 'prod-caramel-choc',
    name: 'Caramel Chocolate',
    flavor: 'Sea Salted Golden Caramel Swirl',
    category: 'caramel',
    tagline: 'Gooey buttery caramel and velvety milk chocolate nestled in crisp wafer.',
    description: 'Lava-like slow-simmered caramel with Brittany Fleur de Sel, enrobed in milk chocolate inside crisp wafers.',
    longDescription: 'A dreamy union of contrasting textures: crispy golden wafer bites encasing a flowing ribbon of amber salted butter caramel, delicately balanced by rich chocolate ganache. Finished with hand-harvested sea salt crystals.',
    price: 15.50,
    originalPrice: 17.00,
    rating: 4.9,
    reviewCount: 356,
    image: caramelImg,
    badge: 'New Sensation',
    cocoaPercentage: 45,
    crispFactor: 9.6,
    sweetnessLevel: 'Rich Caramelized & Salted',
    tastingNotes: ['Salted Butter Toffee', 'Golden Caramel Drip', 'Creamy Milk Cocoa', 'Light Crispy Shell'],
    ingredients: [
      'Gourmet Salted Caramel (Cane Sugar, Heavy Cream, French Butter, Fleur de Sel)',
      'Milk Chocolate (Cacao Mass, Cocoa Butter, Milk Powder)',
      'Wheat Flour',
      'Natural Caramel Essence',
      'Vanilla Bean Caviar'
    ],
    nutrition: {
      servingSize: '4 Bites (30g)',
      calories: 150,
      totalFat: '8g',
      sugar: '12g',
      protein: '2.1g',
    },
    weight: '160g (Approx. 18 Artisan Bites)',
    inStock: true,
  },
  {
    id: 'prod-connoisseur-bundle',
    name: 'The Grand Connoisseur Box',
    flavor: 'All 4 Artisan Flavors in Gold Foil Gift Box',
    category: 'bundle',
    tagline: 'The ultimate tasting journey: Classic, Hazelnut, 72% Dark, and Caramel.',
    description: 'A luxurious keepsake rigid gift box containing full packs of each flavor plus a pairing tasting guide.',
    longDescription: 'Curated for discerning palates and exquisite gift-giving. Presented in an embossed midnight-chocolate and gold-embossed box with 4 individual flavor compartments. Perfect for dinner parties, corporate gifting, or self-indulgence.',
    price: 54.00,
    originalPrice: 65.00,
    rating: 5.0,
    reviewCount: 520,
    image: heroImg,
    badge: 'Luxury Gift Set',
    cocoaPercentage: 55,
    crispFactor: 10.0,
    sweetnessLevel: 'Full Flavor Spectrum',
    tastingNotes: ['Complete Flavor Flight', 'Gold Foil Sealed', 'Includes Sommelier Pairing Guide'],
    ingredients: ['Assortment of all 4 signature recipes made with pure cocoa butter and artisan wafer layers.'],
    nutrition: {
      servingSize: '4 Bites (30g)',
      calories: 148,
      totalFat: '8.5g',
      sugar: '9.5g',
      protein: '2.7g',
    },
    weight: '640g (Approx. 72 Artisan Bites total)',
    inStock: true,
  }
];

export const FLAVOR_PROFILES = [
  {
    id: 'classic',
    title: 'Classic Milk Chocolate',
    subtitle: 'Pure Swiss-Belgian Ganache',
    shortNote: 'Smooth, nostalgic, and intensely satisfying melt-in-the-mouth experience.',
    color: '#8C5332',
    accentColor: '#DFBA49',
    image: classicImg,
    cacao: '48% Cacao',
    crispness: '10/10 Crisp',
    pairing: 'Espresso or Earl Grey Tea',
  },
  {
    id: 'hazelnut',
    title: 'Hazelnut Praline',
    subtitle: 'Fire-Roasted Piedmont Gianduja',
    shortNote: 'Creamy nuttiness paired with crunchy wafer geometry for rich satisfaction.',
    color: '#6B3E26',
    accentColor: '#E6A15C',
    image: hazelnutImg,
    cacao: '52% Cacao',
    crispness: '10/10 Crisp',
    pairing: 'Cappuccino or Aged Tawny Port',
  },
  {
    id: 'dark',
    title: '72% Dark Chocolate',
    subtitle: 'Single-Origin Ecuadorian Arriba',
    shortNote: 'Bold, deep bittersweet intensity with red berry and smoky wood undertones.',
    color: '#3B1E13',
    accentColor: '#C48A54',
    image: darkImg,
    cacao: '72% Cacao',
    crispness: '9.8/10 Crisp',
    pairing: 'Cabernet Sauvignon or Single Malt Whisky',
  },
  {
    id: 'caramel',
    title: 'Caramel & Sea Salt',
    subtitle: 'Amber Slow-Simmered Toffee',
    shortNote: 'Gooey golden salted butter caramel balanced by crisp chocolate wafer crunch.',
    color: '#7D4721',
    accentColor: '#F5B852',
    image: caramelImg,
    cacao: '45% Cacao',
    crispness: '9.7/10 Crisp',
    pairing: 'Hot Vanilla Chai or Champagne',
  },
];
